server:
  enableSwagger: true
  authentication:
    enabled: true
    apiKeys:
      - foo
      - bar
drivers:
  memory:
    maxSize: 20%,
    recovery:
      enabled: true
tracing:
  enabled: true
  exporter: grpc
  url: http://localhost:4317/v1/traces
metrics:
  enabled: true
  exporter: grpc
  url: http://localhost:4317/v1/metrics
