server:
  enableSwagger: true
  authentication:
    enabled: false
    apiKeys:
      - foo
      - bar
  clustering:
    enabled: false
    clusters: 1
drivers:
  memory:
    maxSize: 200
    evictFromOthers: false
    recovery:
      enabled: false
      snapshotInterval: 10
tracing:
  enabled: true
  exporter: grpc
  url: http://localhost:4317/v1/traces
metrics:
  enabled: true
  exporter: grpc
  url: http://localhost:4317/v1/metrics
