receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
      http:
        endpoint: "0.0.0.0:4318"
exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"
  # Jaeger supports OTLP directly. The default port for OTLP/gRPC is 4317
  otlp/jaeger:
    endpoint: "jaeger:4317" # using the docker-compose name of the jaeger container
    tls:
      insecure: true
  logging:
    loglevel: debug
processors:
  batch:
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/jaeger]
    # The exporter name in this pipeline must match the span.metrics_exporter name.
    # The receiver is just a dummy and never used; added to pass validation requiring at least one receiver in a pipeline.
    metrics:
      receivers: [otlp]
      exporters: [prometheus]
